pipelines:
  default:
    - step:
        name: Sync to GitHub
        image: alpine/git
        script:
          - git config --global user.email "tzhang@daoai.com"
          - git config --global user.name "Tom Zhang"
          - git remote add github https://tzhangmc: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@github.com/DaoAI-Robotics-Inc/daoai_world_user_manual.git
          - git push github --all